### ISSUE TITLE
Translate Render WB

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#121]
https://wiki.freecadweb.org/Translating_an_external_workbench

**Comment by howetuft** [comment]
Hello @luzpaz,
I asked Yorik (in PM on the forum) to host Render's translations in the Crowdin "FreeCAD Addons" (https://crowdin.com/project/freecad-addons). In a first exchange he was very enthusiastic, he intended to give me write access to the Crowdin domain, but then he didn't follow up.
I have already sent him a reminder once, but I don't want to harass him either: do you know if he is currently AFK, or how to get his answer otherwise?
Apart from that, everything is ready for translation here...

**Comment by howetuft** [comment]
Hello @Luzpaz,
Thanks to @yorikvanhavre, Render's source strings are now uploaded to Crowdin, waiting for translators... I close the issue.
