### ISSUE TITLE
LuxCore renderer does not  accept AreaLight

### ISSUE THREAD

**Issue by Francisco-Rosa** [FreeCAD/FreeCAD-render#287]
LuxCore renderer

Does not  accept AreaLight.
(https://forum.freecad.org/viewtopic.php?p=693403#p693403)
[Test_animation_render.zip](https://github.com/FreeCAD/FreeCAD-render/files/12328247/Test_animation_render.zip)

**Comment by howetuft** [comment]
Hello,

Sorry, but I cannot reproduce the problem. On my system, I can use AreaLight in Lux without limitation and, for instance, render the LuxCore project in your file above, with just the AL:
![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/38e85eee-d64e-49ed-9123-7ba58f9f9698)

I admit I had to increase significantly the power of the area light, due to the size of the scene (the light is 40 meters above the cube...), but I did not encounter any blocking error...

Could you please describe the steps you followed on your side and the error message you encountered? Thank you very much!

**Comment by Francisco-Rosa** [comment]
Ok, I repeat my tests and I understand what was happening:

1. I was basing on PovRay. PointLights and Arealights are affected by drawing scale (mm or meters) in Cycles, LuxCore and Appleseed, which is expected from physically correct renders, but not for the PovRay.
2. I was working in meters not mm. So, as the objects were in tens of meters it would be necessary to increase the intensity of the Arealights.
3. But Arealights are excessively less powerful than PointLights. The difference in intensity of power applied between them for the same lighting result is about 5000 times! Thus, when replacing a PointLightfor for a AreaLight, it appears that the last one is not on. I believe that these applied intensities should be close if it is possible.

Thank you.

**Comment by howetuft** [comment]
Generally speaking, PovRay should not be used as a reference (and, personally, I would discourage its use).
Among other flaws, PovRay's light management is not very orthodox, and this is particularly the case for Area Lights, which rely on a approximation: https://www.povray.org/documentation/view/3.6.0/313/s. Indeed, this creates a significant gap with the other "physically based" renderers, but the truth is not in PovRay. 

Concerning your file: yes, scene size matters a lot... but just like in real word! For instance, you could think of your 10-meters cube as a building, and you'll immediately perceive that a 2000W light at 40 meters above won't make it illuminated a lot.

Your remark about compared power between PL and AL is partially right, but you should keep in mind that PL and AL have not the same harshness and power distribution, by design, so you should not expect a perfect substitution between both, especially for large AL. Moreover, renderers have not the same calibration for those lights. I had to make choice and I aligned the behavior on Appleseed, which probably provides the less powerful setting for AL...

**Comment by Francisco-Rosa** [comment]
Sorry, but it seems that I was not well understood. When I said "I understand what was happening", that means I understand what was wrong. In summary, I agree that PovRay should not be referenced, of course!

As for the relationship between the point and the light area, I'm not talking about "perfect replacement", but that it shouldn't be that different. In Cycles and LuxCore, if the user exchanges a 100 W PointLight for an AreaLight, he will not expect that he should increase 4 or 5 thousand times the power (500,000 W), that won't make sense to him.

I could be wrong, but in the moment, increasing the size of the AreaLights did not affect the light intensity, only changes the shadows of the illuminated object, right?

**Comment by howetuft** [comment]
> In Cycles and LuxCore, if the user exchanges a 100 W PointLight for an AreaLight, he will not expect that he should increase 4 or 5 thousand times the power (500,000 W), that won't make sense to him.

You're certainly right, I shall  rather calibrate the behavior on LuxCore and Cycles.

> I could be wrong, but in the moment, increasing the size of the AreaLights did not affect the light intensity, only changes the shadows of the illuminated object, right?

You're right. The power is defined for the whole light, not per unit of surface (this is how Lux and Cycles work, and thus I aligned Appleseed, this time...).

**Comment by luzpaz** [comment]
Any reason to keep this open?
