### ISSUE TITLE
Cycles templates are strange

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#309]
The cycles templates seems to be strange.

![Screenshot_20230912_154944](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/023e7c98-8605-4e46-a073-6cb30989b9b8)
“original”

![vgl](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/d367e17d-c89c-4424-9354-49e9cb1be4a8)
Left povray, right cycles, both with studio-light template.

Why is the power-strip glowing out of the holes and the edges on the switch?
Also, colored faces are not honored

**Comment by howetuft** [comment]
Hello,
May you be so kind to attach the .fcstd file, please? I will have a look... Thank you!

**Comment by berberic2** [comment]
I had to recreate the render-targets, because I did not save them. For some unknown reason the coloured faces now show up?! The glowing anomaly still exists in my cycle-render.

[Steckdosen_4-fach_render.FCStd.gz](https://github.com/FreeCAD/FreeCAD-render/files/12598803/Steckdosen_4-fach_render.FCStd.gz)
(I had to gzip it, because github does not like FCStd-files).

**Comment by howetuft** [comment]
Hello,
My explanation:
1. In studio template there is a distant light in direction (-1, 1, -1.5), in order to cast shadows. You can see it neatly in this model:
![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/0b63b207-bfbc-4bfa-a717-2a1b608459ca)
This is what lights the holes and the edges in your model.

2. You use pure white in your model RGB(1,1,1), this is physically incorrect. For the renderer, it means that _all_ incident energy is reflected by the material - absolutely no absorption. That makes the holes glowing in a non-realistic manner. Whereas in physical world, absorption takes place and albedo never exceeds 0.8 (see https://en.wikipedia.org/wiki/Albedo#Terrestrial_albedo). For pure white, it's usually suggested to use RGB(0.8, 0.8, 0.8); for instance, this is the default value for diffuse shader in Blender. My suggestion would be to decrease your white to RGB(0.8, 0.8, 0.8) and then you should get something more realistic (moreover it should help reducing noise in more complex scenes)

By the way, I may increase a bit the distant light intensity in the future for Cycles light studio, your example pointed me out it's a bit weak...

**Comment by berberic2** [comment]
80 % might be physically (more) correct but then the object isn’t white in the rendering but grey.

**Comment by howetuft** [comment]
Update/precision: FreeCAD colors are in sRGB, my suggestion was in RGB.
RGB(0.8, 0.8, 0.8) = sRGB(0.9, 0.9, 0.9) or #e6e6e6, that's what should be entered in FreeCAD
