### ISSUE TITLE
Can someone render this Architectural model with this WB ?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#38]
There is an FC forum thread called [\[Architecture Masterpiece\] Church of The Light](https://forum.freecadweb.org/viewtopic.php?f=24&t=44963). It would really benefit from an actual rendering the image to show how light illuminates the space of the structure. Is there someone interested in making this happen?

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/78792814-9cff3580-797f-11ea-932d-55b03b6d79bb.png)

![image](https://user-images.githubusercontent.com/4140247/78792844-a5577080-797f-11ea-8fa8-9d0ff96e5fda.png)

![image](https://user-images.githubusercontent.com/4140247/78792864-ae484200-797f-11ea-9033-b415d1f7e3a8.png)

**Comment by luzpaz** [comment]
@howetuft what do you think? Care to take a swipe at this?

**Comment by howetuft** [comment]
@luzpaz Yes, with pleasure! Not sure our young Render module is mature enough to meet all expectations, but at least it is an interesting challenge, and also a good use case to feed our roadmap!

**Comment by howetuft** [comment]
@luzpaz (and I may also include @yorikvanhavre into the discussion, if he doesn't mind)

Hi! After several attempts, my conclusion is that our Render module is not yet featured-enough for this task. We lack some key lighting functionalities (sun light for instance, but Hosek-Wilkie skylight and area lights could be of some help as well), some ergonomics (ability to handle a large FreeCAD project into Render WB) and we should also go forward into material handling. So we cannot yet compare with what one can do by exporting the model into Blender and doing all the lighting and the material stuff into that software.

Anyway, this is really a very, very interesting use case. Therefore, I take it as a challenge for our future developments, and I am going to make some additions to the roadmap (in README.md) based on that...

**Comment by justnope** [comment]
@howetuft I really appreciate you wanting the code to be clean. I'm new to python code.

(warning: some bragging ahead :) ) I've made an "upgrade" to the material system: https://github.com/FreeCAD/FreeCAD-render/blob/c59df608bc0c18e39ee91c73c7b33d6706d6f1d1/Materials.md

I've also implemented a system to render multi-layered walls/windows. That code wasn't as clean as you envisioned it, but it worked as a path-finding piece of code.

I've stopped developing the render workbench because it needed a rewrite to make it more optimal. The easiest and last thing I came up with was adjusting the default tesselation parameters. A model from @yorikvanhavre (barcelona?) was complex but 90% was spend in tesselating the ground he had drawn.

Currently we put everything in a string and afterwards, it does a search/replace for those strings to add some parameters. Then it writes that string to disk so some renderers can read it. It's been awhile since I implemented it, but I thought appleseed and luxcore needed seperate project and object definition files.

I could be wrong, but to be ready for large freecad files, we should also be ready to implement a "streaming context". Instead of storing things we already know in memory, we could stream them directly to disk. This doesn't work in the generic rendering case, but it would speed up things for the current renderers.

I hope I made sense about the performance/streaming bit. Feel free to criticize, I haven't implemented it so I could be missing some things.

**Comment by howetuft** [comment]
Hi everybody (if there is still someone listening there...;-)

I made some enhancements in FreeCAD-render, and I was able to get a first rendering of the above scene. Among the enhancements:
- sunsky light, allowing to control sun orientation (and to have it in the axis of the cross, in the present case)
- features to simplify large projects rendering preparation (one can now import groups of parts into a rendering project a single click, and views naming has been apdated as well)

There is still much to do, especially about material and rendering fine tuning (denoising...), but at least there are some visible improvements that I can show. Here are the renderings:

Appleseed:
![appleseed](https://user-images.githubusercontent.com/34142192/83361178-0f403500-a387-11ea-9b69-5bc834a58c1a.png)

Cycles:
![cycles](https://user-images.githubusercontent.com/34142192/83361182-19faca00-a387-11ea-8031-bc130bb68fdd.png)

Lux (a bit burnt and quite noisy):
![Lux](https://user-images.githubusercontent.com/34142192/83361184-1f581480-a387-11ea-855d-ae5fcf69e3a4.png)

@justnope I was notified by mail that you wrote a comment on this thread a few days ago, but I couldn't find your post here, nor answer you... If it is still relevant, could you please post it again?

**Comment by luzpaz** [comment]
@howetuft fantastic progress, thank you for presenting it :smile:

**Comment by justnope** [comment]
@howetuft I'm a bit angry at you. Well, not you as a person but at you as a developer.

When you started this, I already made PRs to add materials, to fix cameras, etc... for several rendering engines. I included fixes to render windows, walls and multi-materials...

This was indeed experimental code, but it worked. You completely tossed away the existing PRs. If you would've just asked what's next, I would've helped you and talked about the current problems rendering a large scene and what's missing. If you've discussed your plans, I would've refactored my code to go from experimental to production.

**Comment by howetuft** [comment]
@justnope Sorry, I don't understand: what PRs are you talking about?

**Comment by justnope** [comment]
https://github.com/FreeCAD/FreeCAD-render/pull/17

**Comment by howetuft** [comment]
OK, thank you for your precisions, because I was actually getting you wrong (not understanding why I should have disturbed anybody about closed unmerged PRs and as I was the only active contributor on the repo for the last 6 months...).
Anyway, yes, any help would be appreciated, there are many things to do in materials field especially. Maybe we can open a thread on FreeCAD forum for that (I have some ideas to share too)...

**Comment by luzpaz** [comment]
Please add the link tot the discussion so we can track it from this ticket

**Comment by justnope** [comment]
What do you mean exactly with "there are many things to do in the materials field"?

Maybe I took the easy way and stored the material properties in the material card in freecad using custom properties. When I needed to render, I wrote an extra serializer for material type X and got the info from the material card.

I've spend most of my time upgrading the serializers to the latest version of the renderers used. Debugging why some models didn't render, adding special cases for multi-materials, clones, etc... Adding code to serialize object vertex data because some renderers needed that... 

I don't deny there's some work to implement materials, but it's not coding work. It's discussing where to store the data and how.

**Comment by howetuft** [comment]
I agree that the main point is: where and how should the rendering material information be stored, and made available to the user.

In my opinion, the key point is FreeCAD is no rendering software, and rendering is just an optional step in objects design.
So we should make rendering material management as easy as possible for user, in a few clicks. Here are some thoughts about it:
First, rendering material should be agnostic about renderer (we cannot require user to be expert in each renderer). Meaning that, in FreeCAD, the user should be able to tell: "this object is glass", optionally tweak a few renderer-independent parameters (e.g., for glass: color, IOR etc.) and then, whatever renderer is used, the object would be rendered as glass. Moreover, the material parameters should have some default values (e.g. for glass, IOR = 1.5), to make on-the-shelf use possible.
So, IMHO, we should provide user with a kind of library of standard rendering materials (glass, matte, glossy coating etc.), a way to apply those materials to objects, and a way to (optionnally) tweak the applied material - all of that in the most friendly and general manner.

If you think your last year code was nearly ready for that, maybe you could rebase, lint/refactor (PEP8) and make a new proposition?
I would suggest focusing first on 2 materials (for instance glass and matte) and 2 renderers, for a proof of concept: are you OK with that?
