### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by mplk** [FreeCAD/FreeCAD-render#78]
Dear all!

I was facing following issue after installing the workbench over the Addon manager. I'm using the portable version. Any ideas how to fix it?

br Martin

![grafik](https://user-images.githubusercontent.com/26392600/93982042-05e93700-fd81-11ea-92c4-3ebc0ea61556.png)

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

**Comment by yorikvanhavre** [comment]
I can't reproduce the problem... Can you describe precisely and step by step what we need to do to see this message? Also, make sure your render addon is up-to-date...

**Comment by howetuft** [comment]
Hello,
Well, it might come from my use of @functools.lru_cache in my recent code (
https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter),
versus your version of Python.
I'm AFK right now but I'll try to investigate it till next week-end (or, if
you can, try to modify code in order to pass an explicit value for maxsize
in calls of @functools.lru_cache, which are in rendermaterials.py
<https://github.com/FreeCAD/FreeCAD-render/blob/41171e9ece5bfe8642ba89da2252165ebdfc863a/rendermaterials.py>,
and
let us know)...

**Comment by mplk** [comment]
I'm using the portabel version (https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x64-portable.7z). I installed the Render Workbanch using the Addon Manager. After restarting I tried to switch to the new installed Workbench. At this point the error occures but the workbench does not open.

**Comment by mplk** [comment]
@howetuft : Thank you! Changing `@functools.lru_cache` to `@functools.lru_cache(maxsize=128)` solved the problem.

**Comment by luzpaz** [comment]
@mplk you should probably consider migrating to 0.19 JFYI.

**Comment by howetuft** [comment]
@mplk Nice, thank you for your feedback! I will fix the code in the master with this correction.

**Comment by howetuft** [comment]
Master fixed (PR #80)
